### ISSUE TITLE
接口不通了？

### ISSUE THREAD

**Issue by 441211324** [lovesnow/ctranslator-sublime3-plugin#5]
` File "C:\Users\Data\Packages\Ctranslator tool\translator.py", line 8, in <module>
    import styled_popup
ImportError: No module named 'styled_popup'`

这个是什么鬼，我看一下貌似是另外一个插件，莫非还依赖了？用的好好今天突然不能用了。

**Comment by smallevilbeast** [comment]
styled_popup
